# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bmeg/vest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bmeg/vest.proto',
  package='bmeg',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x62meg/vest.proto\x12\x04\x62meg\"\xf0\x01\n\tVestScore\x12\x13\n\x0b\x61\x61_mutation\x18\x01 \x01(\t\x12\x0b\n\x03\x61lt\x18\x02 \x01(\t\x12\x12\n\nchromosome\x18\x03 \x01(\t\x12\"\n\x04gene\x18\x04 \x01(\x0b\x32\x14.bmeg.VestScore.Gene\x12\x13\n\x0bprotein_alt\x18\x05 \x01(\t\x12\x13\n\x0bprotein_ref\x18\x06 \x01(\t\x12\x0b\n\x03ref\x18\x07 \x01(\t\x12\r\n\x05score\x18\x08 \x01(\x01\x12\r\n\x05start\x18\t \x01(\x03\x12\x12\n\ntranscript\x18\n \x01(\t\x1a \n\x04Gene\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')
)




_VESTSCORE_GENE = _descriptor.Descriptor(
  name='Gene',
  full_name='bmeg.VestScore.Gene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bmeg.VestScore.Gene.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='bmeg.VestScore.Gene.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=266,
)

_VESTSCORE = _descriptor.Descriptor(
  name='VestScore',
  full_name='bmeg.VestScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aa_mutation', full_name='bmeg.VestScore.aa_mutation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alt', full_name='bmeg.VestScore.alt', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='bmeg.VestScore.chromosome', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gene', full_name='bmeg.VestScore.gene', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protein_alt', full_name='bmeg.VestScore.protein_alt', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protein_ref', full_name='bmeg.VestScore.protein_ref', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ref', full_name='bmeg.VestScore.ref', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='bmeg.VestScore.score', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='bmeg.VestScore.start', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transcript', full_name='bmeg.VestScore.transcript', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VESTSCORE_GENE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=266,
)

_VESTSCORE_GENE.containing_type = _VESTSCORE
_VESTSCORE.fields_by_name['gene'].message_type = _VESTSCORE_GENE
DESCRIPTOR.message_types_by_name['VestScore'] = _VESTSCORE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VestScore = _reflection.GeneratedProtocolMessageType('VestScore', (_message.Message,), dict(

  Gene = _reflection.GeneratedProtocolMessageType('Gene', (_message.Message,), dict(
    DESCRIPTOR = _VESTSCORE_GENE,
    __module__ = 'bmeg.vest_pb2'
    # @@protoc_insertion_point(class_scope:bmeg.VestScore.Gene)
    ))
  ,
  DESCRIPTOR = _VESTSCORE,
  __module__ = 'bmeg.vest_pb2'
  # @@protoc_insertion_point(class_scope:bmeg.VestScore)
  ))
_sym_db.RegisterMessage(VestScore)
_sym_db.RegisterMessage(VestScore.Gene)


# @@protoc_insertion_point(module_scope)
