// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bmeg/genome.proto

package bmeg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A `Position` is one or more (consecutive***) bases in some `Reference`. A `Position` is
// represented by a `Reference` name, and a base number on that `Reference`
// (0-based).
// ***Modified from GA4GH to include end position.***
type Position struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// The name of the `Reference` on which the `Position` is located.
	// (e.g. `chr20` or `X`)
	Chromosome string `protobuf:"bytes,3,opt,name=chromosome" json:"chromosome,omitempty"`
	// The 0-based offset from the start of the forward strand for that
	// `Reference`. Genomic positions are non-negative integers less than
	// `Reference` length.
	//
	// For Variant Calls: The start position at which this variant occurs (0-based).
	// This corresponds to the first base of the string of reference bases.
	// Genomic positions are non-negative integers less than reference length.
	// Variants spanning the join of circular genomes are represented as
	// two variants one on each side of the join (position 0).
	Start int64 `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	// The end position (exclusive), resulting in [start, end) closed-open
	// interval.
	//
	// For Variantcalls: This is typically calculated by `start + referenceBases.length`.
	End int64 `protobuf:"varint,5,opt,name=end" json:"end,omitempty"`
	// Strand the position is associated with.
	Strand string `protobuf:"bytes,6,opt,name=strand" json:"strand,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Position) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Position) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Position) GetChromosome() string {
	if m != nil {
		return m.Chromosome
	}
	return ""
}

func (m *Position) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Position) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Position) GetStrand() string {
	if m != nil {
		return m.Strand
	}
	return ""
}

// Annotation of a contiguous region of a sequence.
// An example might be a gene or a protein.
// For example, a position X might corresponds to gene/Feature TP53.
type Gene struct {
	// ensembl id
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Symbol      string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	SeqId       string `protobuf:"bytes,4,opt,name=seqId" json:"seqId,omitempty"`
	Start       int32  `protobuf:"varint,5,opt,name=start" json:"start,omitempty"`
	End         int32  `protobuf:"varint,6,opt,name=end" json:"end,omitempty"`
	Strand      string `protobuf:"bytes,7,opt,name=strand" json:"strand,omitempty"`
	Accession   string `protobuf:"bytes,8,opt,name=accession" json:"accession,omitempty"`
	Refseq      string `protobuf:"bytes,9,opt,name=refseq" json:"refseq,omitempty"`
	// Name/value attributes of the annotation.  Attribute names follow the GFF3
	// naming convention of reserved names starting with an upper cases
	// character, and user-define names start with lower-case.  Most GFF3
	// pre-defined attributes apply, the exceptions are ID and Parent, which are
	// defined as fields. Additional, the following attributes are added:
	// * Score - the GFF3 score column
	// * Phase - the GFF3 phase column for CDS features.
	Info map[string]string `protobuf:"bytes,11,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Gene) Reset()                    { *m = Gene{} }
func (m *Gene) String() string            { return proto.CompactTextString(m) }
func (*Gene) ProtoMessage()               {}
func (*Gene) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Gene) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gene) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Gene) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Gene) GetSeqId() string {
	if m != nil {
		return m.SeqId
	}
	return ""
}

func (m *Gene) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Gene) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Gene) GetStrand() string {
	if m != nil {
		return m.Strand
	}
	return ""
}

func (m *Gene) GetAccession() string {
	if m != nil {
		return m.Accession
	}
	return ""
}

func (m *Gene) GetRefseq() string {
	if m != nil {
		return m.Refseq
	}
	return ""
}

func (m *Gene) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

type Exon struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Parent string `protobuf:"bytes,2,opt,name=parent" json:"parent,omitempty"`
	SeqId  string `protobuf:"bytes,3,opt,name=seqId" json:"seqId,omitempty"`
	Start  int32  `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	End    int32  `protobuf:"varint,5,opt,name=end" json:"end,omitempty"`
	Strand string `protobuf:"bytes,6,opt,name=strand" json:"strand,omitempty"`
}

func (m *Exon) Reset()                    { *m = Exon{} }
func (m *Exon) String() string            { return proto.CompactTextString(m) }
func (*Exon) ProtoMessage()               {}
func (*Exon) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Exon) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Exon) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Exon) GetSeqId() string {
	if m != nil {
		return m.SeqId
	}
	return ""
}

func (m *Exon) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Exon) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Exon) GetStrand() string {
	if m != nil {
		return m.Strand
	}
	return ""
}

type Transcript struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Parent string `protobuf:"bytes,2,opt,name=parent" json:"parent,omitempty"`
	Symbol string `protobuf:"bytes,3,opt,name=symbol" json:"symbol,omitempty"`
	SeqId  string `protobuf:"bytes,4,opt,name=seqId" json:"seqId,omitempty"`
	Start  int32  `protobuf:"varint,5,opt,name=start" json:"start,omitempty"`
	End    int32  `protobuf:"varint,6,opt,name=end" json:"end,omitempty"`
	Strand string `protobuf:"bytes,7,opt,name=strand" json:"strand,omitempty"`
}

func (m *Transcript) Reset()                    { *m = Transcript{} }
func (m *Transcript) String() string            { return proto.CompactTextString(m) }
func (*Transcript) ProtoMessage()               {}
func (*Transcript) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Transcript) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transcript) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Transcript) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Transcript) GetSeqId() string {
	if m != nil {
		return m.SeqId
	}
	return ""
}

func (m *Transcript) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Transcript) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Transcript) GetStrand() string {
	if m != nil {
		return m.Strand
	}
	return ""
}

type GeneSynonym struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid    string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Symbol string `protobuf:"bytes,4,opt,name=symbol" json:"symbol,omitempty"`
	// Target: Gene
	SynonymFor []string `protobuf:"bytes,5,rep,name=synonymFor" json:"synonymFor,omitempty"`
	// Target: GeneDatabase
	InDatabase []string `protobuf:"bytes,6,rep,name=inDatabase" json:"inDatabase,omitempty"`
}

func (m *GeneSynonym) Reset()                    { *m = GeneSynonym{} }
func (m *GeneSynonym) String() string            { return proto.CompactTextString(m) }
func (*GeneSynonym) ProtoMessage()               {}
func (*GeneSynonym) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GeneSynonym) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneSynonym) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GeneSynonym) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeneSynonym) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GeneSynonym) GetSynonymFor() []string {
	if m != nil {
		return m.SynonymFor
	}
	return nil
}

func (m *GeneSynonym) GetInDatabase() []string {
	if m != nil {
		return m.InDatabase
	}
	return nil
}

type GeneDatabase struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid  string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Name string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *GeneDatabase) Reset()                    { *m = GeneDatabase{} }
func (m *GeneDatabase) String() string            { return proto.CompactTextString(m) }
func (*GeneDatabase) ProtoMessage()               {}
func (*GeneDatabase) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GeneDatabase) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneDatabase) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GeneDatabase) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeneDatabase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GeneFamily struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gid         string `protobuf:"bytes,2,opt,name=gid" json:"gid,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Tag         string `protobuf:"bytes,4,opt,name=tag" json:"tag,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
}

func (m *GeneFamily) Reset()                    { *m = GeneFamily{} }
func (m *GeneFamily) String() string            { return proto.CompactTextString(m) }
func (*GeneFamily) ProtoMessage()               {}
func (*GeneFamily) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GeneFamily) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneFamily) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GeneFamily) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GeneFamily) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GeneFamily) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Position)(nil), "bmeg.Position")
	proto.RegisterType((*Gene)(nil), "bmeg.Gene")
	proto.RegisterType((*Exon)(nil), "bmeg.Exon")
	proto.RegisterType((*Transcript)(nil), "bmeg.Transcript")
	proto.RegisterType((*GeneSynonym)(nil), "bmeg.GeneSynonym")
	proto.RegisterType((*GeneDatabase)(nil), "bmeg.GeneDatabase")
	proto.RegisterType((*GeneFamily)(nil), "bmeg.GeneFamily")
}

func init() { proto.RegisterFile("bmeg/genome.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0x38, 0x09, 0x9b, 0x29, 0x42, 0xc5, 0x5a, 0xad, 0x2c, 0x84, 0x56, 0x51, 0x4e,
	0x3d, 0x15, 0x09, 0x0e, 0x20, 0xce, 0xec, 0xa2, 0xbd, 0xa1, 0xc2, 0x81, 0xab, 0xdb, 0x4c, 0x8b,
	0x45, 0x63, 0x77, 0x6d, 0xb3, 0x22, 0x77, 0xce, 0xbc, 0x00, 0x37, 0x5e, 0x84, 0x57, 0x43, 0x63,
	0xa7, 0x9b, 0xfe, 0x3b, 0xa0, 0x95, 0xb8, 0xcd, 0xf7, 0xb9, 0x9e, 0xfe, 0x3c, 0x9f, 0x26, 0xf0,
	0x74, 0xde, 0xe2, 0xea, 0xc5, 0x0a, 0xb5, 0x69, 0x71, 0xba, 0xb1, 0xc6, 0x1b, 0x9e, 0x91, 0x55,
	0xff, 0x4c, 0xe0, 0xec, 0x83, 0x71, 0xca, 0x2b, 0xa3, 0xf9, 0x13, 0x48, 0x55, 0x23, 0x92, 0x2a,
	0x99, 0x94, 0xb3, 0x54, 0x35, 0x9c, 0x43, 0xe6, 0xbb, 0x0d, 0x8a, 0x34, 0x38, 0xa1, 0xe6, 0x97,
	0x00, 0x8b, 0x2f, 0xd6, 0xb4, 0xc6, 0x99, 0x16, 0x05, 0x0b, 0x27, 0x3b, 0x0e, 0x3f, 0x87, 0xdc,
	0x79, 0x69, 0xbd, 0xc8, 0xaa, 0x64, 0xc2, 0x66, 0x51, 0xf0, 0x31, 0x30, 0xd4, 0x8d, 0xc8, 0x83,
	0x47, 0x25, 0xbf, 0x80, 0xc2, 0x79, 0x2b, 0x75, 0x23, 0x8a, 0xd0, 0xa3, 0x57, 0xf5, 0x9f, 0x14,
	0xb2, 0xf7, 0xa8, 0xf1, 0x08, 0x86, 0x2e, 0x74, 0xed, 0xdc, 0xac, 0x7b, 0x9c, 0x5e, 0xf1, 0x0a,
	0x46, 0x0d, 0xba, 0x85, 0x55, 0x1b, 0x7a, 0x43, 0x4f, 0xb4, 0x6b, 0x05, 0x24, 0xbc, 0xbd, 0x69,
	0x02, 0x52, 0x39, 0x8b, 0x62, 0x00, 0x25, 0xa8, 0xfc, 0x00, 0xb4, 0x08, 0xde, 0x01, 0xe8, 0xa3,
	0x5d, 0x50, 0xfe, 0x1c, 0x4a, 0xb9, 0x58, 0xa0, 0x73, 0xf4, 0xaf, 0x67, 0xe1, 0x68, 0x30, 0xe8,
	0x96, 0xc5, 0xa5, 0xc3, 0x5b, 0x51, 0xc6, 0x5b, 0x51, 0xf1, 0x09, 0x64, 0x4a, 0x2f, 0x8d, 0x18,
	0x55, 0x6c, 0x32, 0x7a, 0x79, 0x3e, 0xa5, 0x10, 0xa6, 0xf4, 0xde, 0xe9, 0x8d, 0x5e, 0x9a, 0x2b,
	0xed, 0x6d, 0x37, 0x0b, 0xbf, 0x78, 0xf6, 0x1a, 0xca, 0x7b, 0x8b, 0xb0, 0xbe, 0x62, 0xd7, 0x4f,
	0x83, 0x4a, 0xc2, 0xbf, 0x93, 0xeb, 0x6f, 0xdb, 0x70, 0xa2, 0x78, 0x9b, 0xbe, 0x49, 0xea, 0x1f,
	0x09, 0x64, 0x57, 0xdf, 0x4f, 0xc4, 0x79, 0x01, 0xc5, 0x46, 0x5a, 0xd4, 0x7e, 0x3b, 0xc1, 0xa8,
	0x86, 0xf9, 0xb0, 0x93, 0xf3, 0xc9, 0x4e, 0xcc, 0x27, 0x3f, 0x35, 0x9f, 0xfd, 0x20, 0x7f, 0x27,
	0x00, 0x9f, 0xac, 0xd4, 0x31, 0x87, 0x7f, 0x86, 0x19, 0x62, 0x66, 0x7b, 0x31, 0xff, 0x97, 0x10,
	0xeb, 0x5f, 0x09, 0x8c, 0x68, 0xfa, 0x1f, 0x3b, 0x6d, 0x74, 0xd7, 0x1e, 0x51, 0x8e, 0x81, 0xad,
	0x54, 0xd3, 0x23, 0x52, 0x79, 0xbf, 0x13, 0x6c, 0x67, 0x27, 0x06, 0xe6, 0x6c, 0x8f, 0xf9, 0x12,
	0xc0, 0xc5, 0xc6, 0xd7, 0xc6, 0x8a, 0xbc, 0x62, 0xb4, 0x2b, 0x83, 0x43, 0xe7, 0x4a, 0xbf, 0x93,
	0x5e, 0xce, 0xa5, 0x43, 0x51, 0xc4, 0xf3, 0xc1, 0xa9, 0x3f, 0xc3, 0x63, 0x82, 0xdb, 0xea, 0x07,
	0xd2, 0x71, 0xc8, 0xb4, 0x6c, 0xb1, 0x67, 0x0b, 0x75, 0x7d, 0x07, 0x40, 0x9d, 0xaf, 0x65, 0xab,
	0xd6, 0xdd, 0x03, 0xfb, 0x8e, 0x81, 0x79, 0xb9, 0xea, 0xdb, 0x52, 0x79, 0xb8, 0x8a, 0xf9, 0xd1,
	0x2a, 0xce, 0x8b, 0xf0, 0xed, 0x79, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x22, 0xfd, 0xa9, 0x1e,
	0x90, 0x04, 0x00, 0x00,
}
