// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bmeg/phenotype.proto

package bmeg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResponseSummary_SummaryType int32

const (
	ResponseSummary_UNKNOWN       ResponseSummary_SummaryType = 0
	ResponseSummary_EC50          ResponseSummary_SummaryType = 1
	ResponseSummary_IC50          ResponseSummary_SummaryType = 2
	ResponseSummary_AC50          ResponseSummary_SummaryType = 3
	ResponseSummary_LD50          ResponseSummary_SummaryType = 4
	ResponseSummary_GR50          ResponseSummary_SummaryType = 5
	ResponseSummary_AMAX          ResponseSummary_SummaryType = 6
	ResponseSummary_AUC           ResponseSummary_SummaryType = 7
	ResponseSummary_ACTIVITY_AREA ResponseSummary_SummaryType = 8
	ResponseSummary_RMSE          ResponseSummary_SummaryType = 9
)

var ResponseSummary_SummaryType_name = map[int32]string{
	0: "UNKNOWN",
	1: "EC50",
	2: "IC50",
	3: "AC50",
	4: "LD50",
	5: "GR50",
	6: "AMAX",
	7: "AUC",
	8: "ACTIVITY_AREA",
	9: "RMSE",
}
var ResponseSummary_SummaryType_value = map[string]int32{
	"UNKNOWN":       0,
	"EC50":          1,
	"IC50":          2,
	"AC50":          3,
	"LD50":          4,
	"GR50":          5,
	"AMAX":          6,
	"AUC":           7,
	"ACTIVITY_AREA": 8,
	"RMSE":          9,
}

func (x ResponseSummary_SummaryType) String() string {
	return proto.EnumName(ResponseSummary_SummaryType_name, int32(x))
}
func (ResponseSummary_SummaryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor6, []int{6, 0}
}

type ResponseCurve_ResponseType int32

const (
	ResponseCurve_UNKNOWN  ResponseCurve_ResponseType = 0
	ResponseCurve_GROWTH   ResponseCurve_ResponseType = 1
	ResponseCurve_ACTIVITY ResponseCurve_ResponseType = 2
)

var ResponseCurve_ResponseType_name = map[int32]string{
	0: "UNKNOWN",
	1: "GROWTH",
	2: "ACTIVITY",
}
var ResponseCurve_ResponseType_value = map[string]int32{
	"UNKNOWN":  0,
	"GROWTH":   1,
	"ACTIVITY": 2,
}

func (x ResponseCurve_ResponseType) String() string {
	return proto.EnumName(ResponseCurve_ResponseType_name, int32(x))
}
func (ResponseCurve_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor6, []int{8, 0}
}

//
// Gene Ontology
type GeneOntologyTerm struct {
	Id         string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Namespace  string   `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	Definition string   `protobuf:"bytes,4,opt,name=definition" json:"definition,omitempty"`
	Comment    string   `protobuf:"bytes,5,opt,name=comment" json:"comment,omitempty"`
	Synonym    []string `protobuf:"bytes,6,rep,name=synonym" json:"synonym,omitempty"`
	IsA        []string `protobuf:"bytes,7,rep,name=is_a,json=isA" json:"is_a,omitempty"`
	AltId      []string `protobuf:"bytes,8,rep,name=alt_id,json=altId" json:"alt_id,omitempty"`
	Subset     []string `protobuf:"bytes,9,rep,name=subset" json:"subset,omitempty"`
	Xref       []string `protobuf:"bytes,10,rep,name=xref" json:"xref,omitempty"`
	IsObsolete bool     `protobuf:"varint,11,opt,name=is_obsolete,json=isObsolete" json:"is_obsolete,omitempty"`
	Consider   []string `protobuf:"bytes,12,rep,name=consider" json:"consider,omitempty"`
}

func (m *GeneOntologyTerm) Reset()                    { *m = GeneOntologyTerm{} }
func (m *GeneOntologyTerm) String() string            { return proto.CompactTextString(m) }
func (*GeneOntologyTerm) ProtoMessage()               {}
func (*GeneOntologyTerm) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *GeneOntologyTerm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneOntologyTerm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GeneOntologyTerm) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GeneOntologyTerm) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *GeneOntologyTerm) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *GeneOntologyTerm) GetSynonym() []string {
	if m != nil {
		return m.Synonym
	}
	return nil
}

func (m *GeneOntologyTerm) GetIsA() []string {
	if m != nil {
		return m.IsA
	}
	return nil
}

func (m *GeneOntologyTerm) GetAltId() []string {
	if m != nil {
		return m.AltId
	}
	return nil
}

func (m *GeneOntologyTerm) GetSubset() []string {
	if m != nil {
		return m.Subset
	}
	return nil
}

func (m *GeneOntologyTerm) GetXref() []string {
	if m != nil {
		return m.Xref
	}
	return nil
}

func (m *GeneOntologyTerm) GetIsObsolete() bool {
	if m != nil {
		return m.IsObsolete
	}
	return false
}

func (m *GeneOntologyTerm) GetConsider() []string {
	if m != nil {
		return m.Consider
	}
	return nil
}

type GeneOntologyAnnotation struct {
	Title      string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Genes      []string `protobuf:"bytes,2,rep,name=genes" json:"genes,omitempty"`
	Functions  []string `protobuf:"bytes,3,rep,name=functions" json:"functions,omitempty"`
	Evidence   []string `protobuf:"bytes,4,rep,name=evidence" json:"evidence,omitempty"`
	References []string `protobuf:"bytes,5,rep,name=references" json:"references,omitempty"`
}

func (m *GeneOntologyAnnotation) Reset()                    { *m = GeneOntologyAnnotation{} }
func (m *GeneOntologyAnnotation) String() string            { return proto.CompactTextString(m) }
func (*GeneOntologyAnnotation) ProtoMessage()               {}
func (*GeneOntologyAnnotation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *GeneOntologyAnnotation) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GeneOntologyAnnotation) GetGenes() []string {
	if m != nil {
		return m.Genes
	}
	return nil
}

func (m *GeneOntologyAnnotation) GetFunctions() []string {
	if m != nil {
		return m.Functions
	}
	return nil
}

func (m *GeneOntologyAnnotation) GetEvidence() []string {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *GeneOntologyAnnotation) GetReferences() []string {
	if m != nil {
		return m.References
	}
	return nil
}

type Compound struct {
	Id          string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Target      []string `protobuf:"bytes,3,rep,name=target" json:"target,omitempty"`
	Description []string `protobuf:"bytes,4,rep,name=description" json:"description,omitempty"`
	Synonyms    []string `protobuf:"bytes,5,rep,name=synonyms" json:"synonyms,omitempty"`
	Pubmed      []string `protobuf:"bytes,6,rep,name=pubmed" json:"pubmed,omitempty"`
	Report      string   `protobuf:"bytes,7,opt,name=report" json:"report,omitempty"`
	Status      string   `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	Rationale   string   `protobuf:"bytes,9,opt,name=rationale" json:"rationale,omitempty"`
	Smiles      string   `protobuf:"bytes,10,opt,name=smiles" json:"smiles,omitempty"`
	Assays      []string `protobuf:"bytes,11,rep,name=assays" json:"assays,omitempty"`
	Source      []string `protobuf:"bytes,12,rep,name=source" json:"source,omitempty"`
	Sids        []string `protobuf:"bytes,13,rep,name=sids" json:"sids,omitempty"`
	ChebiId     string   `protobuf:"bytes,14,opt,name=chebi_id,json=chebiId" json:"chebi_id,omitempty"`
}

func (m *Compound) Reset()                    { *m = Compound{} }
func (m *Compound) String() string            { return proto.CompactTextString(m) }
func (*Compound) ProtoMessage()               {}
func (*Compound) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *Compound) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Compound) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Compound) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Compound) GetDescription() []string {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Compound) GetSynonyms() []string {
	if m != nil {
		return m.Synonyms
	}
	return nil
}

func (m *Compound) GetPubmed() []string {
	if m != nil {
		return m.Pubmed
	}
	return nil
}

func (m *Compound) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

func (m *Compound) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Compound) GetRationale() string {
	if m != nil {
		return m.Rationale
	}
	return ""
}

func (m *Compound) GetSmiles() string {
	if m != nil {
		return m.Smiles
	}
	return ""
}

func (m *Compound) GetAssays() []string {
	if m != nil {
		return m.Assays
	}
	return nil
}

func (m *Compound) GetSource() []string {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Compound) GetSids() []string {
	if m != nil {
		return m.Sids
	}
	return nil
}

func (m *Compound) GetChebiId() string {
	if m != nil {
		return m.ChebiId
	}
	return ""
}

type Assay struct {
	Id           string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Sid          string           `protobuf:"bytes,2,opt,name=sid" json:"sid,omitempty"`
	Name         string           `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Cellline     string           `protobuf:"bytes,4,opt,name=cellline" json:"cellline,omitempty"`
	Pubmed       []string         `protobuf:"bytes,5,rep,name=pubmed" json:"pubmed,omitempty"`
	Drugresponse []*ResponseCurve `protobuf:"bytes,6,rep,name=drugresponse" json:"drugresponse,omitempty"`
	GeneTarget   []string         `protobuf:"bytes,7,rep,name=gene_target,json=geneTarget" json:"gene_target,omitempty"`
}

func (m *Assay) Reset()                    { *m = Assay{} }
func (m *Assay) String() string            { return proto.CompactTextString(m) }
func (*Assay) ProtoMessage()               {}
func (*Assay) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *Assay) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Assay) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *Assay) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Assay) GetCellline() string {
	if m != nil {
		return m.Cellline
	}
	return ""
}

func (m *Assay) GetPubmed() []string {
	if m != nil {
		return m.Pubmed
	}
	return nil
}

func (m *Assay) GetDrugresponse() []*ResponseCurve {
	if m != nil {
		return m.Drugresponse
	}
	return nil
}

func (m *Assay) GetGeneTarget() []string {
	if m != nil {
		return m.GeneTarget
	}
	return nil
}

type FDAApproval struct {
	CompoundId            string `protobuf:"bytes,1,opt,name=compound_id,json=compoundId" json:"compound_id,omitempty"`
	Approved              string `protobuf:"bytes,2,opt,name=approved" json:"approved,omitempty"`
	ApprovedData          string `protobuf:"bytes,3,opt,name=approved_data,json=approvedData" json:"approved_data,omitempty"`
	Company               string `protobuf:"bytes,4,opt,name=company" json:"company,omitempty"`
	Summary               string `protobuf:"bytes,5,opt,name=summary" json:"summary,omitempty"`
	GeneralInformation    string `protobuf:"bytes,6,opt,name=general_information,json=generalInformation" json:"general_information,omitempty"`
	ClinicalResults       string `protobuf:"bytes,7,opt,name=clinical_results,json=clinicalResults" json:"clinical_results,omitempty"`
	SideEffects           string `protobuf:"bytes,8,opt,name=side_effects,json=sideEffects" json:"side_effects,omitempty"`
	MechanismOfAction     string `protobuf:"bytes,9,opt,name=mechanism_of_action,json=mechanismOfAction" json:"mechanism_of_action,omitempty"`
	AdditionalInformation string `protobuf:"bytes,10,opt,name=additional_information,json=additionalInformation" json:"additional_information,omitempty"`
	TheraputicAreas       string `protobuf:"bytes,11,opt,name=theraputic_areas,json=theraputicAreas" json:"theraputic_areas,omitempty"`
}

func (m *FDAApproval) Reset()                    { *m = FDAApproval{} }
func (m *FDAApproval) String() string            { return proto.CompactTextString(m) }
func (*FDAApproval) ProtoMessage()               {}
func (*FDAApproval) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *FDAApproval) GetCompoundId() string {
	if m != nil {
		return m.CompoundId
	}
	return ""
}

func (m *FDAApproval) GetApproved() string {
	if m != nil {
		return m.Approved
	}
	return ""
}

func (m *FDAApproval) GetApprovedData() string {
	if m != nil {
		return m.ApprovedData
	}
	return ""
}

func (m *FDAApproval) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *FDAApproval) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *FDAApproval) GetGeneralInformation() string {
	if m != nil {
		return m.GeneralInformation
	}
	return ""
}

func (m *FDAApproval) GetClinicalResults() string {
	if m != nil {
		return m.ClinicalResults
	}
	return ""
}

func (m *FDAApproval) GetSideEffects() string {
	if m != nil {
		return m.SideEffects
	}
	return ""
}

func (m *FDAApproval) GetMechanismOfAction() string {
	if m != nil {
		return m.MechanismOfAction
	}
	return ""
}

func (m *FDAApproval) GetAdditionalInformation() string {
	if m != nil {
		return m.AdditionalInformation
	}
	return ""
}

func (m *FDAApproval) GetTheraputicAreas() string {
	if m != nil {
		return m.TheraputicAreas
	}
	return ""
}

type DoseResponse struct {
	Dose     float64 `protobuf:"fixed64,1,opt,name=dose" json:"dose,omitempty"`
	Response float64 `protobuf:"fixed64,2,opt,name=response" json:"response,omitempty"`
}

func (m *DoseResponse) Reset()                    { *m = DoseResponse{} }
func (m *DoseResponse) String() string            { return proto.CompactTextString(m) }
func (*DoseResponse) ProtoMessage()               {}
func (*DoseResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *DoseResponse) GetDose() float64 {
	if m != nil {
		return m.Dose
	}
	return 0
}

func (m *DoseResponse) GetResponse() float64 {
	if m != nil {
		return m.Response
	}
	return 0
}

type ResponseSummary struct {
	Type  ResponseSummary_SummaryType `protobuf:"varint,1,opt,name=type,enum=bmeg.ResponseSummary_SummaryType" json:"type,omitempty"`
	Value float64                     `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	Unit  string                      `protobuf:"bytes,3,opt,name=unit" json:"unit,omitempty"`
}

func (m *ResponseSummary) Reset()                    { *m = ResponseSummary{} }
func (m *ResponseSummary) String() string            { return proto.CompactTextString(m) }
func (*ResponseSummary) ProtoMessage()               {}
func (*ResponseSummary) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *ResponseSummary) GetType() ResponseSummary_SummaryType {
	if m != nil {
		return m.Type
	}
	return ResponseSummary_UNKNOWN
}

func (m *ResponseSummary) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ResponseSummary) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type CompoundElement struct {
	Compound string  `protobuf:"bytes,1,opt,name=compound" json:"compound,omitempty"`
	Ratio    float64 `protobuf:"fixed64,3,opt,name=ratio" json:"ratio,omitempty"`
}

func (m *CompoundElement) Reset()                    { *m = CompoundElement{} }
func (m *CompoundElement) String() string            { return proto.CompactTextString(m) }
func (*CompoundElement) ProtoMessage()               {}
func (*CompoundElement) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *CompoundElement) GetCompound() string {
	if m != nil {
		return m.Compound
	}
	return ""
}

func (m *CompoundElement) GetRatio() float64 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

type ResponseCurve struct {
	Gid            string                     `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	AssayId        string                     `protobuf:"bytes,2,opt,name=assay_id,json=assayId" json:"assay_id,omitempty"`
	ResponseType   ResponseCurve_ResponseType `protobuf:"varint,3,opt,name=responseType,enum=bmeg.ResponseCurve_ResponseType" json:"responseType,omitempty"`
	Values         []*DoseResponse            `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	GrowthStandard float64                    `protobuf:"fixed64,5,opt,name=growthStandard" json:"growthStandard,omitempty"`
	Compounds      []*CompoundElement         `protobuf:"bytes,6,rep,name=compounds" json:"compounds,omitempty"`
	Sample         string                     `protobuf:"bytes,7,opt,name=sample" json:"sample,omitempty"`
	Summary        []*ResponseSummary         `protobuf:"bytes,8,rep,name=summary" json:"summary,omitempty"`
	Controls       []float64                  `protobuf:"fixed64,9,rep,packed,name=controls" json:"controls,omitempty"`
	Blanks         []float64                  `protobuf:"fixed64,10,rep,packed,name=blanks" json:"blanks,omitempty"`
	Source         string                     `protobuf:"bytes,11,opt,name=source" json:"source,omitempty"`
}

func (m *ResponseCurve) Reset()                    { *m = ResponseCurve{} }
func (m *ResponseCurve) String() string            { return proto.CompactTextString(m) }
func (*ResponseCurve) ProtoMessage()               {}
func (*ResponseCurve) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *ResponseCurve) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *ResponseCurve) GetAssayId() string {
	if m != nil {
		return m.AssayId
	}
	return ""
}

func (m *ResponseCurve) GetResponseType() ResponseCurve_ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return ResponseCurve_UNKNOWN
}

func (m *ResponseCurve) GetValues() []*DoseResponse {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ResponseCurve) GetGrowthStandard() float64 {
	if m != nil {
		return m.GrowthStandard
	}
	return 0
}

func (m *ResponseCurve) GetCompounds() []*CompoundElement {
	if m != nil {
		return m.Compounds
	}
	return nil
}

func (m *ResponseCurve) GetSample() string {
	if m != nil {
		return m.Sample
	}
	return ""
}

func (m *ResponseCurve) GetSummary() []*ResponseSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

func (m *ResponseCurve) GetControls() []float64 {
	if m != nil {
		return m.Controls
	}
	return nil
}

func (m *ResponseCurve) GetBlanks() []float64 {
	if m != nil {
		return m.Blanks
	}
	return nil
}

func (m *ResponseCurve) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type AssayData struct {
	AssayId    string             `protobuf:"bytes,1,opt,name=assay_id,json=assayId" json:"assay_id,omitempty"`
	CompoundId string             `protobuf:"bytes,2,opt,name=compound_id,json=compoundId" json:"compound_id,omitempty"`
	Active     bool               `protobuf:"varint,3,opt,name=active" json:"active,omitempty"`
	Comment    string             `protobuf:"bytes,4,opt,name=comment" json:"comment,omitempty"`
	FloatVals  map[string]float64 `protobuf:"bytes,5,rep,name=float_vals,json=floatVals" json:"float_vals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringVals map[string]string  `protobuf:"bytes,6,rep,name=string_vals,json=stringVals" json:"string_vals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntVals    map[string]int32   `protobuf:"bytes,7,rep,name=int_vals,json=intVals" json:"int_vals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *AssayData) Reset()                    { *m = AssayData{} }
func (m *AssayData) String() string            { return proto.CompactTextString(m) }
func (*AssayData) ProtoMessage()               {}
func (*AssayData) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

func (m *AssayData) GetAssayId() string {
	if m != nil {
		return m.AssayId
	}
	return ""
}

func (m *AssayData) GetCompoundId() string {
	if m != nil {
		return m.CompoundId
	}
	return ""
}

func (m *AssayData) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *AssayData) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *AssayData) GetFloatVals() map[string]float64 {
	if m != nil {
		return m.FloatVals
	}
	return nil
}

func (m *AssayData) GetStringVals() map[string]string {
	if m != nil {
		return m.StringVals
	}
	return nil
}

func (m *AssayData) GetIntVals() map[string]int32 {
	if m != nil {
		return m.IntVals
	}
	return nil
}

type Evidence struct {
	// ECO or OBI is recommended
	EvidenceType *OntologyTerm `protobuf:"bytes,1,opt,name=evidence_type,json=evidenceType" json:"evidence_type,omitempty"`
	// A textual description of the evidence. This is used to complement the
	// structured description in the evidence_type field
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// URLs of supporting publications
	Publications []string `protobuf:"bytes,3,rep,name=publications" json:"publications,omitempty"`
	// AMP/ASCO/CAP Guidelines
	EvidenceLabel string `protobuf:"bytes,4,opt,name=evidence_label,json=evidenceLabel" json:"evidence_label,omitempty"`
	// description of response
	ResponseType string `protobuf:"bytes,5,opt,name=response_type,json=responseType" json:"response_type,omitempty"`
	// oncogenic description
	Oncogenic string `protobuf:"bytes,6,opt,name=oncogenic" json:"oncogenic,omitempty"`
	// passed from harvested source
	EvidenceLevel string `protobuf:"bytes,7,opt,name=evidence_level,json=evidenceLevel" json:"evidence_level,omitempty"`
	// Additional annotation data.
	Info *google_protobuf.Struct `protobuf:"bytes,9,opt,name=info" json:"info,omitempty"`
}

func (m *Evidence) Reset()                    { *m = Evidence{} }
func (m *Evidence) String() string            { return proto.CompactTextString(m) }
func (*Evidence) ProtoMessage()               {}
func (*Evidence) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{10} }

func (m *Evidence) GetEvidenceType() *OntologyTerm {
	if m != nil {
		return m.EvidenceType
	}
	return nil
}

func (m *Evidence) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Evidence) GetPublications() []string {
	if m != nil {
		return m.Publications
	}
	return nil
}

func (m *Evidence) GetEvidenceLabel() string {
	if m != nil {
		return m.EvidenceLabel
	}
	return ""
}

func (m *Evidence) GetResponseType() string {
	if m != nil {
		return m.ResponseType
	}
	return ""
}

func (m *Evidence) GetOncogenic() string {
	if m != nil {
		return m.Oncogenic
	}
	return ""
}

func (m *Evidence) GetEvidenceLevel() string {
	if m != nil {
		return m.EvidenceLevel
	}
	return ""
}

func (m *Evidence) GetInfo() *google_protobuf.Struct {
	if m != nil {
		return m.Info
	}
	return nil
}

type Phenotype struct {
	// optional id of Phenotype
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// reference
	Type *OntologyTerm `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// text
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// text description of taxonomy
	Family string `protobuf:"bytes,4,opt,name=family" json:"family,omitempty"`
}

func (m *Phenotype) Reset()                    { *m = Phenotype{} }
func (m *Phenotype) String() string            { return proto.CompactTextString(m) }
func (*Phenotype) ProtoMessage()               {}
func (*Phenotype) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{11} }

func (m *Phenotype) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Phenotype) GetType() *OntologyTerm {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Phenotype) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Phenotype) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

type G2PAssociation struct {
	// optional id of associatation
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// gene ids
	Genes []string `protobuf:"bytes,2,rep,name=genes" json:"genes,omitempty"`
	// environment (drug) ids
	Environments []string `protobuf:"bytes,3,rep,name=environments" json:"environments,omitempty"`
	// phenotype (disease) ids
	Phenotypes []string `protobuf:"bytes,4,rep,name=phenotypes" json:"phenotypes,omitempty"`
	// feature (variant) ids
	Features []string `protobuf:"bytes,5,rep,name=features" json:"features,omitempty"`
	// A textual description of the evidence. This is used to complement the
	// structured description in the evidence_type field
	Description string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	// structured evidence
	Evidence []*Evidence `protobuf:"bytes,7,rep,name=evidence" json:"evidence,omitempty"`
	// name of source evidence was harvested from
	Source string `protobuf:"bytes,8,opt,name=source" json:"source,omitempty"`
	// opaque data harvested from source
	Original *google_protobuf.Struct `protobuf:"bytes,9,opt,name=original" json:"original,omitempty"`
}

func (m *G2PAssociation) Reset()                    { *m = G2PAssociation{} }
func (m *G2PAssociation) String() string            { return proto.CompactTextString(m) }
func (*G2PAssociation) ProtoMessage()               {}
func (*G2PAssociation) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{12} }

func (m *G2PAssociation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *G2PAssociation) GetGenes() []string {
	if m != nil {
		return m.Genes
	}
	return nil
}

func (m *G2PAssociation) GetEnvironments() []string {
	if m != nil {
		return m.Environments
	}
	return nil
}

func (m *G2PAssociation) GetPhenotypes() []string {
	if m != nil {
		return m.Phenotypes
	}
	return nil
}

func (m *G2PAssociation) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *G2PAssociation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *G2PAssociation) GetEvidence() []*Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *G2PAssociation) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *G2PAssociation) GetOriginal() *google_protobuf.Struct {
	if m != nil {
		return m.Original
	}
	return nil
}

func init() {
	proto.RegisterType((*GeneOntologyTerm)(nil), "bmeg.GeneOntologyTerm")
	proto.RegisterType((*GeneOntologyAnnotation)(nil), "bmeg.GeneOntologyAnnotation")
	proto.RegisterType((*Compound)(nil), "bmeg.Compound")
	proto.RegisterType((*Assay)(nil), "bmeg.Assay")
	proto.RegisterType((*FDAApproval)(nil), "bmeg.FDAApproval")
	proto.RegisterType((*DoseResponse)(nil), "bmeg.DoseResponse")
	proto.RegisterType((*ResponseSummary)(nil), "bmeg.ResponseSummary")
	proto.RegisterType((*CompoundElement)(nil), "bmeg.CompoundElement")
	proto.RegisterType((*ResponseCurve)(nil), "bmeg.ResponseCurve")
	proto.RegisterType((*AssayData)(nil), "bmeg.AssayData")
	proto.RegisterType((*Evidence)(nil), "bmeg.Evidence")
	proto.RegisterType((*Phenotype)(nil), "bmeg.Phenotype")
	proto.RegisterType((*G2PAssociation)(nil), "bmeg.G2PAssociation")
	proto.RegisterEnum("bmeg.ResponseSummary_SummaryType", ResponseSummary_SummaryType_name, ResponseSummary_SummaryType_value)
	proto.RegisterEnum("bmeg.ResponseCurve_ResponseType", ResponseCurve_ResponseType_name, ResponseCurve_ResponseType_value)
}

func init() { proto.RegisterFile("bmeg/phenotype.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 1571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdd, 0x6e, 0x23, 0x49,
	0x15, 0xc6, 0xff, 0xf6, 0xb1, 0xe3, 0x78, 0x2a, 0x3b, 0xa1, 0x89, 0xa2, 0xdd, 0x6c, 0x23, 0x56,
	0xcb, 0x22, 0x39, 0xa3, 0x8c, 0xa2, 0x41, 0x2b, 0x16, 0x61, 0x25, 0xd9, 0x60, 0xb1, 0x3b, 0x59,
	0x75, 0xb2, 0x33, 0x70, 0xd5, 0x2a, 0x77, 0x97, 0x9d, 0xd2, 0x74, 0x57, 0xb5, 0xba, 0xaa, 0x0d,
	0x96, 0xe0, 0x55, 0x78, 0x07, 0x24, 0xee, 0x78, 0x00, 0x2e, 0x78, 0x00, 0xae, 0xb9, 0xe7, 0x82,
	0x47, 0x40, 0xa7, 0xaa, 0xba, 0xdd, 0x76, 0x06, 0x0d, 0x57, 0xae, 0xef, 0xab, 0x3a, 0x5d, 0xa7,
	0xce, 0xbf, 0xe1, 0xa3, 0x45, 0xca, 0x56, 0xe7, 0xd9, 0x23, 0x13, 0x52, 0x6f, 0x32, 0x36, 0xcd,
	0x72, 0xa9, 0x25, 0x69, 0x23, 0x7b, 0x72, 0xba, 0x92, 0x72, 0x95, 0xb0, 0x73, 0xc3, 0x2d, 0x8a,
	0xe5, 0xb9, 0xd2, 0x79, 0x11, 0x69, 0x7b, 0xe6, 0xe4, 0xc8, 0x48, 0x46, 0x09, 0x17, 0x3c, 0xa2,
	0x89, 0x25, 0xfd, 0xbf, 0x35, 0x61, 0x72, 0xcb, 0x04, 0xbb, 0x13, 0x5a, 0x26, 0x72, 0xb5, 0x79,
	0x60, 0x79, 0x4a, 0xc6, 0xd0, 0xe4, 0xb1, 0xd7, 0x38, 0x6b, 0x7c, 0x3e, 0x08, 0x9a, 0x3c, 0x26,
	0x04, 0xda, 0x82, 0xa6, 0xcc, 0x6b, 0x1a, 0xc6, 0xac, 0xc9, 0x29, 0x0c, 0xf0, 0x57, 0x65, 0x34,
	0x62, 0x5e, 0xcb, 0x6c, 0x6c, 0x09, 0xf2, 0x31, 0x40, 0xcc, 0x96, 0x5c, 0x70, 0xcd, 0xa5, 0xf0,
	0xda, 0x66, 0xbb, 0xc6, 0x10, 0x0f, 0x7a, 0x91, 0x4c, 0x53, 0x26, 0xb4, 0xd7, 0x31, 0x9b, 0x25,
	0xc4, 0x1d, 0xb5, 0x11, 0x52, 0x6c, 0x52, 0xaf, 0x7b, 0xd6, 0xc2, 0x1d, 0x07, 0xc9, 0x33, 0x68,
	0x73, 0x15, 0x52, 0xaf, 0x67, 0xe8, 0x16, 0x57, 0x33, 0xf2, 0x1c, 0xba, 0x34, 0xd1, 0x21, 0x8f,
	0xbd, 0xbe, 0x21, 0x3b, 0x34, 0xd1, 0xf3, 0x98, 0x1c, 0x43, 0x57, 0x15, 0x0b, 0xc5, 0xb4, 0x37,
	0x30, 0xb4, 0x43, 0xf8, 0x8e, 0x3f, 0xe4, 0x6c, 0xe9, 0x81, 0x61, 0xcd, 0x9a, 0x7c, 0x02, 0x43,
	0xae, 0x42, 0xb9, 0x50, 0x32, 0x61, 0x9a, 0x79, 0xc3, 0xb3, 0xc6, 0xe7, 0xfd, 0x00, 0xb8, 0xba,
	0x73, 0x0c, 0x39, 0x81, 0x7e, 0x24, 0x85, 0xe2, 0x31, 0xcb, 0xbd, 0x91, 0x11, 0xac, 0xb0, 0xff,
	0xe7, 0x06, 0x1c, 0xd7, 0xad, 0x37, 0x13, 0x42, 0x6a, 0x6a, 0x5e, 0xf8, 0x11, 0x74, 0x34, 0xd7,
	0x09, 0x73, 0x66, 0xb4, 0x00, 0xd9, 0x15, 0x13, 0x4c, 0x79, 0x4d, 0xab, 0xaf, 0x01, 0x68, 0xcb,
	0x65, 0x21, 0x22, 0x94, 0x53, 0x5e, 0xcb, 0xec, 0x6c, 0x09, 0x54, 0x80, 0xad, 0x79, 0xcc, 0x44,
	0xc4, 0xbc, 0xb6, 0x55, 0xa0, 0xc4, 0x68, 0xe7, 0x9c, 0x2d, 0x59, 0x8e, 0x40, 0x79, 0x1d, 0xb3,
	0x5b, 0x63, 0xfc, 0x7f, 0x35, 0xa1, 0x7f, 0x25, 0xd3, 0x4c, 0x16, 0x22, 0xfe, 0xbf, 0xdc, 0x7a,
	0x0c, 0x5d, 0x4d, 0xf3, 0x15, 0xd3, 0x4e, 0x0f, 0x87, 0xc8, 0x19, 0x0c, 0x63, 0xa6, 0xa2, 0x9c,
	0x67, 0xce, 0xa3, 0xb8, 0x59, 0xa7, 0x50, 0x4d, 0xe7, 0xa9, 0x52, 0x91, 0x0a, 0xe3, 0x57, 0xb3,
	0x62, 0x91, 0xb2, 0xd8, 0xf9, 0xd4, 0x21, 0xe4, 0x73, 0x96, 0xc9, 0x5c, 0x7b, 0x3d, 0xa3, 0x83,
	0x43, 0xc6, 0x81, 0x9a, 0xea, 0x42, 0x79, 0x7d, 0xcb, 0x5b, 0x84, 0x86, 0xca, 0x8d, 0x79, 0x69,
	0xc2, 0xbc, 0x81, 0x0d, 0xba, 0x8a, 0x30, 0x52, 0x29, 0x4f, 0x98, 0xf2, 0xc0, 0x49, 0x19, 0x84,
	0x3c, 0x55, 0x8a, 0x6e, 0x94, 0x37, 0xb4, 0xb7, 0x5b, 0x64, 0xce, 0xcb, 0x22, 0x8f, 0x98, 0xf3,
	0xab, 0x43, 0x68, 0x17, 0xc5, 0x63, 0xe5, 0x1d, 0xd8, 0x30, 0xc1, 0x35, 0xf9, 0x11, 0xf4, 0xa3,
	0x47, 0xb6, 0xe0, 0x18, 0x6b, 0x63, 0x17, 0xb1, 0x88, 0xe7, 0xb1, 0xff, 0x8f, 0x06, 0x74, 0x66,
	0xf8, 0xc5, 0x27, 0x06, 0x9e, 0x40, 0x4b, 0xf1, 0xd8, 0xd9, 0x17, 0x97, 0x95, 0xc9, 0x5b, 0x35,
	0x93, 0x63, 0x80, 0xb1, 0x24, 0x49, 0xb8, 0x60, 0x2e, 0x53, 0x2a, 0x5c, 0x33, 0x5c, 0x67, 0xc7,
	0x70, 0xaf, 0x60, 0x14, 0xe7, 0xc5, 0x2a, 0x67, 0x2a, 0x93, 0x42, 0x31, 0x63, 0xd6, 0xe1, 0xc5,
	0xd1, 0x14, 0x53, 0x7c, 0x1a, 0x38, 0xf6, 0xaa, 0xc8, 0xd7, 0x2c, 0xd8, 0x39, 0x88, 0xe1, 0x8e,
	0x31, 0x17, 0x3a, 0x27, 0xdb, 0x5c, 0x02, 0xa4, 0x1e, 0x0c, 0xe3, 0xff, 0xb5, 0x05, 0xc3, 0xaf,
	0xaf, 0x67, 0xb3, 0x2c, 0xcb, 0xe5, 0x9a, 0x26, 0x28, 0x10, 0xb9, 0x00, 0x0a, 0xab, 0xc7, 0x41,
	0x49, 0xcd, 0x63, 0x54, 0x9f, 0x9a, 0xc3, 0xac, 0x7c, 0x69, 0x85, 0xc9, 0x8f, 0xe1, 0xa0, 0x5c,
	0x87, 0x31, 0xd5, 0xd4, 0xbd, 0x7b, 0x54, 0x92, 0xd7, 0x54, 0x53, 0x57, 0x0b, 0x32, 0x2a, 0x36,
	0xee, 0xf9, 0x25, 0x34, 0xb5, 0xa0, 0x48, 0x53, 0x9a, 0x6f, 0xca, 0x2a, 0xe1, 0x20, 0x39, 0x87,
	0x23, 0xd4, 0x39, 0xa7, 0x49, 0xc8, 0xc5, 0x52, 0xe6, 0xa9, 0x09, 0x02, 0xaf, 0x6b, 0x4e, 0x11,
	0xb7, 0x35, 0xdf, 0xee, 0x90, 0x9f, 0xc2, 0xa4, 0xac, 0x7c, 0x61, 0xce, 0x54, 0x91, 0x68, 0xe5,
	0x62, 0xee, 0xb0, 0xe4, 0x03, 0x4b, 0x93, 0x4f, 0x61, 0x84, 0xd9, 0x1d, 0xb2, 0xe5, 0x92, 0x45,
	0xba, 0x0c, 0xc1, 0x21, 0x72, 0x37, 0x96, 0x22, 0x53, 0x38, 0x4a, 0x59, 0xf4, 0x48, 0x05, 0x57,
	0x69, 0x28, 0x97, 0x21, 0x35, 0xa9, 0xea, 0x22, 0xf2, 0x59, 0xb5, 0x75, 0xb7, 0x9c, 0x99, 0x0d,
	0x72, 0x09, 0xc7, 0x34, 0x8e, 0xb9, 0x0d, 0xd4, 0x1d, 0x8d, 0x6d, 0xa4, 0x3e, 0xdf, 0xee, 0xee,
	0x29, 0xad, 0x1f, 0x59, 0x4e, 0xb3, 0x42, 0xf3, 0x28, 0xa4, 0x39, 0xa3, 0xca, 0x14, 0xa8, 0x41,
	0x70, 0xb8, 0xe5, 0x67, 0x48, 0xfb, 0xbf, 0x84, 0xd1, 0xb5, 0x54, 0xac, 0x74, 0x3d, 0x06, 0x5a,
	0x2c, 0x95, 0xad, 0x3e, 0x8d, 0xc0, 0xac, 0xd1, 0x53, 0x55, 0xc0, 0x34, 0x0d, 0x5f, 0x61, 0xff,
	0x3f, 0x0d, 0x38, 0x2c, 0x85, 0xef, 0x9d, 0x91, 0x2f, 0xa1, 0x8d, 0x2d, 0xc6, 0x7c, 0x63, 0x7c,
	0xf1, 0xe9, 0x6e, 0x70, 0xb9, 0x43, 0x53, 0xf7, 0xfb, 0xb0, 0xc9, 0x58, 0x60, 0x8e, 0x63, 0x8d,
	0x5b, 0xd3, 0xa4, 0x28, 0xef, 0xb0, 0x00, 0x15, 0x2a, 0x04, 0xd7, 0x65, 0xe4, 0xe3, 0xda, 0xff,
	0x23, 0x0c, 0x6b, 0xe2, 0x64, 0x08, 0xbd, 0xef, 0x5f, 0xff, 0xe6, 0xf5, 0xdd, 0xdb, 0xd7, 0x93,
	0x1f, 0x90, 0x3e, 0xb4, 0x6f, 0xae, 0x2e, 0x5f, 0x4c, 0x1a, 0xb8, 0x9a, 0xe3, 0xaa, 0x89, 0xab,
	0x19, 0xae, 0x5a, 0xb8, 0xfa, 0xe6, 0xfa, 0xf2, 0xc5, 0xa4, 0x8d, 0xab, 0xdb, 0xe0, 0xf2, 0xc5,
	0xa4, 0x63, 0x76, 0xbf, 0x9d, 0xfd, 0x76, 0xd2, 0x25, 0x3d, 0x68, 0xcd, 0xbe, 0xbf, 0x9a, 0xf4,
	0xc8, 0x33, 0x38, 0x98, 0x5d, 0x3d, 0xcc, 0xdf, 0xcc, 0x1f, 0x7e, 0x17, 0xce, 0x82, 0x9b, 0xd9,
	0xa4, 0x8f, 0xa7, 0x82, 0x6f, 0xef, 0x6f, 0x26, 0x03, 0xff, 0x0a, 0x0e, 0xcb, 0xd2, 0x78, 0x93,
	0x30, 0xd3, 0x7c, 0x4c, 0xad, 0xb7, 0x94, 0x8b, 0xf4, 0x0a, 0xe3, 0xb3, 0x4c, 0xa9, 0x31, 0x2f,
	0x68, 0x04, 0x16, 0xf8, 0xff, 0x6c, 0xc1, 0xc1, 0x4e, 0xbe, 0x61, 0xd2, 0xaf, 0xaa, 0x44, 0xc1,
	0x25, 0xd6, 0x0e, 0x53, 0x71, 0xc2, 0xaa, 0x16, 0xf4, 0x0c, 0x9e, 0xc7, 0xe4, 0x1a, 0x46, 0xa5,
	0x0b, 0xd0, 0x04, 0xe6, 0xdb, 0xe3, 0x8b, 0xb3, 0xf7, 0xe4, 0x71, 0x85, 0x8c, 0xa5, 0x77, 0xa4,
	0xc8, 0x17, 0xd0, 0x35, 0x46, 0x56, 0xa6, 0x2e, 0x0f, 0x2f, 0x88, 0x95, 0xaf, 0x07, 0x44, 0xe0,
	0x4e, 0x90, 0xcf, 0x60, 0xbc, 0xca, 0xe5, 0xef, 0xf5, 0xe3, 0xbd, 0xa6, 0x22, 0xa6, 0x79, 0x6c,
	0x52, 0xab, 0x11, 0xec, 0xb1, 0xe4, 0x25, 0x0c, 0xca, 0xa7, 0x2b, 0x57, 0x5e, 0x9e, 0xdb, 0xcf,
	0xee, 0x19, 0x2d, 0xd8, 0x9e, 0x33, 0x15, 0x95, 0xa6, 0x59, 0xc2, 0xca, 0x7a, 0x6e, 0x11, 0x39,
	0xdf, 0x26, 0x72, 0xbf, 0xfe, 0xa9, 0xbd, 0x60, 0xda, 0xe6, 0xb7, 0x6d, 0xba, 0x3a, 0x97, 0x89,
	0x32, 0x3d, 0xbc, 0x11, 0x54, 0x18, 0x2f, 0x59, 0x24, 0x54, 0xbc, 0x53, 0xa6, 0x8f, 0x37, 0x02,
	0x87, 0x6a, 0xe5, 0x7c, 0xe8, 0x2e, 0x37, 0xc8, 0xbf, 0x84, 0x51, 0xdd, 0x76, 0xbb, 0x61, 0x06,
	0xd0, 0xbd, 0x0d, 0xee, 0xde, 0x3e, 0xfc, 0x7a, 0xd2, 0x20, 0x23, 0xe8, 0x97, 0xd1, 0x32, 0x69,
	0xfa, 0xff, 0x6e, 0xc1, 0xc0, 0x94, 0x75, 0x53, 0xa4, 0xea, 0x3e, 0x6c, 0xec, 0xfa, 0x70, 0xaf,
	0x42, 0x36, 0x9f, 0x54, 0x48, 0xec, 0x3f, 0x91, 0xe6, 0x6b, 0xeb, 0xde, 0x7e, 0xe0, 0x50, 0x7d,
	0x08, 0x6a, 0xef, 0x0e, 0x41, 0x5f, 0x01, 0x2c, 0x13, 0x49, 0x75, 0xb8, 0xa6, 0x89, 0xed, 0xa6,
	0xc3, 0x8b, 0x8f, 0xad, 0xc9, 0x2a, 0x95, 0xa6, 0x5f, 0xe3, 0x89, 0x37, 0x34, 0x51, 0x37, 0x42,
	0xe7, 0x9b, 0x60, 0xb0, 0x2c, 0x31, 0xf9, 0x15, 0x0c, 0x95, 0xce, 0xb9, 0x58, 0x59, 0x79, 0xeb,
	0xbd, 0x4f, 0xf6, 0xe5, 0xef, 0xcd, 0x91, 0xed, 0x07, 0x40, 0x55, 0x04, 0x79, 0x05, 0x7d, 0x2e,
	0xdc, 0xf5, 0x3d, 0x23, 0x7e, 0xba, 0x2f, 0x3e, 0x17, 0xb5, 0xcb, 0x7b, 0xdc, 0xa2, 0x93, 0x5f,
	0xc0, 0x78, 0x57, 0x2f, 0xcc, 0x87, 0x77, 0x6c, 0x53, 0xe6, 0xc3, 0x3b, 0xb6, 0x79, 0x7f, 0x81,
	0xf8, 0xb2, 0xf9, 0xf3, 0xc6, 0xc9, 0x57, 0x70, 0xb8, 0xa7, 0xd5, 0x87, 0xc4, 0x07, 0x75, 0xf1,
	0x2f, 0x61, 0x54, 0xd7, 0xea, 0x43, 0xb2, 0x9d, 0x9a, 0xac, 0xff, 0xf7, 0x26, 0xf4, 0x6f, 0xca,
	0xb1, 0xea, 0x15, 0x1c, 0x94, 0x23, 0x56, 0x58, 0x95, 0xc0, 0x2a, 0xaf, 0xea, 0xb3, 0x72, 0x30,
	0x2a, 0x0f, 0x9a, 0xd8, 0xda, 0x1b, 0x93, 0xac, 0x86, 0x3b, 0x63, 0x92, 0x0f, 0xa3, 0xac, 0x58,
	0x24, 0x3c, 0xa2, 0xf5, 0x71, 0x6f, 0x87, 0x23, 0x3f, 0x81, 0x71, 0x75, 0x7d, 0x42, 0x17, 0x2c,
	0x71, 0xf1, 0x51, 0x29, 0xf5, 0x0d, 0x92, 0xd8, 0x5d, 0xcb, 0x32, 0x60, 0xb5, 0xb4, 0x4d, 0x72,
	0xb7, 0x36, 0x9c, 0xc2, 0x40, 0x8a, 0x48, 0xae, 0x98, 0xe0, 0x91, 0xeb, 0x8f, 0x5b, 0x62, 0xf7,
	0x26, 0xb6, 0x66, 0x89, 0x4b, 0xdc, 0xed, 0x4d, 0x48, 0x92, 0x9f, 0x41, 0x1b, 0x9b, 0x96, 0x69,
	0x70, 0xc3, 0x8b, 0x1f, 0x4e, 0xed, 0xff, 0x8c, 0x69, 0xf9, 0x3f, 0x03, 0x43, 0xa9, 0x88, 0x74,
	0x60, 0x0e, 0xf9, 0x7f, 0x82, 0xc1, 0x77, 0xe5, 0xdf, 0x93, 0x27, 0x23, 0xd1, 0x67, 0xae, 0xa7,
	0x34, 0xff, 0xa7, 0x41, 0x6d, 0x13, 0xd9, 0x33, 0x64, 0xeb, 0xa9, 0x21, 0x8f, 0xa1, 0xbb, 0xa4,
	0x29, 0x4f, 0xca, 0xa9, 0xc1, 0x21, 0xff, 0x2f, 0x4d, 0x18, 0xdf, 0x5e, 0x7c, 0x37, 0x53, 0x4a,
	0x46, 0xdc, 0xf6, 0xd1, 0x7d, 0x25, 0xde, 0x3f, 0x85, 0xfb, 0x30, 0x62, 0x62, 0xcd, 0x73, 0x29,
	0x30, 0x07, 0x2b, 0xcf, 0xd4, 0x39, 0x9c, 0xb7, 0xab, 0xbf, 0x5e, 0xca, 0x4d, 0xc1, 0x35, 0x06,
	0xeb, 0xd6, 0x92, 0x51, 0x5d, 0xe4, 0xd5, 0x34, 0x5e, 0xe1, 0xfd, 0x27, 0x75, 0x9f, 0x3e, 0xe9,
	0x8b, 0xda, 0xa4, 0x6f, 0xb3, 0x6e, 0x6c, 0x0d, 0x54, 0x06, 0x66, 0x6d, 0xf2, 0xdf, 0x56, 0xbb,
	0x7e, 0xbd, 0xda, 0x91, 0x97, 0xd0, 0x97, 0x39, 0x5f, 0x71, 0x41, 0x93, 0x0f, 0xb9, 0xab, 0x3a,
	0xb8, 0xe8, 0x9a, 0xad, 0x97, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x89, 0x93, 0x38, 0x4c, 0x5d,
	0x0e, 0x00, 0x00,
}
